groups/urls.py
from django.urls import path,re_path
from . import views

app_name = 'groups'

urlpatterns = [
    path('',views.ListGroup.as_view(),name='all'),
    path('new/',views.CreateGroup.as_view(),name='create'),
    path('create/', views.CreatePost.as_view(), name='create_post'),
    re_path(r'^posts/in/(?P<slug>[-\w]+)$',views.SingleGroup.as_view(),name='single'),
    re_path(r'^join/(?P<slug>[-\w]+)$',views.JoinGroup.as_view(),name='join'),
    re_path(r'^leave/(?P<slug>[-\w]+)$',views.LeaveGroup.as_view(),name='leave'),
]

posts/urls.py
from django.urls import path,re_path
from . import views

app_name = 'posts'

urlpatterns = [
    path('',views.PostList.as_view(),name='all'),
    path('new/',views.CreateRegularPost.as_view(),name='create'),
    path('create/', views.CreatePost.as_view(), name='create_post'),
    re_path(r'^by/(?P<username>[-\w]+)$',views.UserPosts.as_view(),name='for_user'),
    re_path(r'^by/(?P<username>[-\w]+)/(?P<pk>\d+)$',views.PostDetail.as_view(),name='single'),
    re_path(r'^delete/(?P<pk>\d+)$',views.DeletePost.as_view(),name='delete'),
]

# path('newpost/',views.CreatePost.as_view(),name='group_post'),

zepharis/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("",views.HomePage.as_view(),name="home"),
    path('test/', views.TestPage.as_view(), name="test"),
    path('thanks/', views.ThanksPage.as_view(), name="thanks"),
    path("accounts/",include('accounts.urls',namespace='accounts')),
    path("accounts/",include('django.contrib.auth.urls')),
    path("posts/",include('posts.urls',namespace='posts')),
    path("groups/",include('groups.urls',namespace='groups')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

groups/models.py
from django.db import models
from django.utils.text import slugify
from django.urls import reverse

# Create your models here.
import misaka 

from django.contrib.auth import get_user_model
User = get_user_model()

from django import template
register =  template.Library()


class Group(models.Model):
    name = models.CharField(max_length=255,unique=True)
    slug = models.SlugField(allow_unicode=True,unique=True)
    description = models.TextField(blank=True,default='')
    description_html = models.TextField(editable=False,default='',blank=True)
    members = models.ManyToManyField(User,through='GroupMember')
    posts = models.ManyToManyField('posts.Post', related_name='groups', blank=True)


    def __self__(self):
        return self.name
    
    def save(self,*args,**kwargs):
        self.slug = slugify(self.name)
        self.description_html = misaka.html(self.description)
        super().save(*args,**kwargs)

    def get_absolute_url(self):
        return reverse('groups:single',kwargs={'slug':self.slug})
    
    def member_count(self):
        return self.members.count()

    def post_count(self):
        return self.group_posts.count()
    
    class Meta:
        ordering = ['name']
    

class GroupMember(models.Model):
    group = models.ForeignKey(Group,related_name='membership', on_delete=models.CASCADE)
    user = models.ForeignKey(User,related_name='user_groups', on_delete=models.CASCADE)

    def __str__(self):
        return self.user.get_username()
    
    class Meta:
        unique_together = ('group','user')
    pass
    

class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now=True)
    message = models.TextField()
    image = models.ImageField(upload_to='post_images/', blank=True, null=True)  # Add an ImageField
    message_html = models.TextField(editable=False)
    group = models.ForeignKey('Group', on_delete=models.CASCADE)

    def __str__(self):
        return self.message
    
    def save(self,*args,**kwargs):
        self.message_html = misaka.html(self.message)
        super().save(*args,**kwargs)

    def get_absolute_url(self):
        return reverse('posts:single',kwargs={'username':self.user.username,'pk':self.pk})
    
    class Meta:
        ordering = ['-created_at']
        unique_together = ['user','message']

groups/forms.py
from django import forms
from .models import Post  # Import your Post model

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['message', 'image']  # Adjust fields as per your Post model

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # You can customize form fields here if needed
        # For instance, setting attributes or initial values

groups/views.py
from typing import Any
from django.shortcuts import render, redirect
from django.contrib import messages
from . import models

# Create your views here.
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.views import generic
from django.shortcuts import get_object_or_404

from groups.models import Group,GroupMember

from django.db.utils import IntegrityError

from .forms import PostForm
from posts.models import Post



class CreateGroup(LoginRequiredMixin,generic.CreateView):
    fields = ('name','description')
    model = Group

class SingleGroup(generic.DetailView):
    model = Group
    template_name = 'groups/group_detail.html'  # Update with your actual template name

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # Retrieve the posts related to the current group
        context['post_list'] = self.object.group_posts.all()

        return context

class ListGroup(generic.ListView):
    model = Group

class JoinGroup(LoginRequiredMixin,generic.RedirectView):
    def get_redirect_url(self,*args,**kwargs):
        return reverse('groups:single',kwargs={'slug':self.kwargs.get('slug')})
    
    def get(self,request,*args,**kwargs):
        group = get_object_or_404(Group,slug=self.kwargs.get('slug'))

        try:
            GroupMember.objects.create(user=self.request.user,group=group)
        except IntegrityError:
            messages.warning(self.request,'Warning already a member!')
        else:
            messages.success(self.request,'You are now a member!')

        return super().get(request,*args,**kwargs)
        


class LeaveGroup(LoginRequiredMixin,generic.RedirectView):
    def get_redirect_url(self,*args,**kwargs):
        return reverse('groups:single',kwargs={'slug':self.kwargs.get('slug')})
    
    def get(self,request,*args,**kwargs):

        try:
            membership = models.GroupMember.objects.filter(
                user=self.request.user,
                group__slug=self.kwargs.get('slug')
            ).get()
        except models.GroupMember.DoesNotExist:
            messages.warning(self.request,'Sorry you are not in this group!')
        else:
            membership.delete()
            messages.success(self.request,'You have left the group!')
        return super().get(request,*args,**kwargs)
    
class CreatePost(LoginRequiredMixin, generic.CreateView):
    form_class = PostForm
    model = Post
    template_name = 'groups/group_detail.html'  # Update with your actual template name

    def form_valid(self, form):
        group_id = self.request.POST.get('group')
        group = get_object_or_404(Group, id=group_id)

        if self.request.user in group.members.all():
            self.object = form.save(commit=False)
            self.object.user = self.request.user
            self.object.group = group

            # Handle the image upload
            if 'image' in self.request.FILES:
                self.object.image = self.request.FILES['image']

            self.object.save()

            messages.success(self.request, 'Post created successfully.')
            return redirect('posts:single', username=self.request.user.username, pk=self.object.pk)
        else:
            form.add_error(None, 'You are not a member of this group. Cannot create a post.')
            return self.render_to_response(self.get_context_data(form=form))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['groups'] = Group.objects.all()  # Provide groups to the template
        return context
    
    

groups/templates/groups/group_base.html
{% extends "base.html" %}

{% block content %}
<div class="container">
    <div class="row">
        {% block pregroup %}{% endblock %}
        {% block group_content %}{% endblock %}
        {% block postgroup %}{% endblock %}

    </div>

</div>

{% endblock %}

groups/templates/groups/group_detail.html
{% extends "groups/group_base.html" %}

{% block pregroup %}
    <h1>{{ group.name }}</h1>
    <h2>Member Count: {{ group.member_count }}</h2>

    <div class="content">
        {% if user in group.members.all %}
            <a href="{% url 'groups:leave' slug=group.slug %}" class="btn btn-lg btn-fill btn-warning">
                <i class="fa-sharp fa-solid fa-circle-xmark"></i>Leave
            </a>
        {% else %}
            <a href="{% url 'groups:join' slug=group.slug %}" class="btn btn-lg btn-fill btn-warning">
                <i class="fa-solid fa-circle-check"></i>Join
            </a>
        {% endif %}
    </div>
{% endblock %}

{% block group_content %}
    {% load bootstrap5 %}
    <br>
    <br>
    <div class="col-md-8">
        <form id="postForm" action="{% url 'posts:create_post' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.non_field_errors }}
            <br>
            <button type="submit" class="btn btn-primary">Post</button>
        </form>
        <br>
        <br>
        <br>

        {% if group.post_count == 0 %}
            <h2>No posts in this group yet!</h2>
        {% else %}
            {% for post in post_list %}
                {% include 'posts/_post.html' %}
            {% endfor %}
        {% endif %}
    </div>
{% endblock %}

groups/templates/groups/group_form.html
{% extends "groups/group_base.html" %}

{% load bootstrap5 %}

{% block group_content %}
<div class="container">
    <h4>Create New Group</h4>
    <form action="{% url 'groups:create' %}" method="POST" id="groupForm">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
        <button type="submit" class="btn btn-primary btn-large">Create</button>
        {% endbuttons %}
    </form>
</div>
{% endblock %}

groups/templates/groups/group_list.html
{% extends "groups/group_base.html" %}

{% block pregroup %}
<div class="col-md-4">
    <div class="content">
        {% if user.is_authenticated %}
        <h2>Welcome Back!
            <a href="{% url 'posts:for_user' username=user.username %}">
                @{{user.username}}
            </a>
        </h2>
        {% endif %}
        <h2>Groups</h2>
        <p>Welcome to the groups page!</p>

    </div>
    {% if user.is_authenticated %}
    <a href="{% url 'groups:create' %}" class="btn btn-md btn-fill btn-warning"><i class="fa-solid fa-plus"></i>Create New Group!</a>
    {% endif %}

</div>
{% endblock %}


{% block group_content %}
<div class="col-md-8">
    <div class="list-group">
        {% for group in object_list %}
            <a href="{% url 'groups:single' slug=group.slug %}" class="list-group-item list-group-item-action flex-column align-items-start">
                <h3 class="mb-1">{{ group.name }}</h3>
                <p class="mb-1">{{ group.description_html|safe }}</p>
                <div class="d-flex w-40 justify-content-between">
                    <small class="text-muted">
                        <!-- Debugging: Display member count details -->
                        Member Count: {{ group.member_count }}<br>
                        <!-- Member Count (Field): {{ group.members.count }}</span> -->
                    </small>
                    <small class="text-muted">
                        <!-- Debugging: Display post count details -->
                        Post Count: {{ group.post_count }}<br>
                        <!-- Post Count (Field): {{ group.posts.count }}</span> -->
                    </small>
                    <span></span><span></span>
                </div>
            </a>
            <!-- Debugging: Display the entire group object -->
            <!-- <pre>{{ group|safe }}</pre> -->
        {% endfor %}
    </div>
</div>


{% endblock %}