accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from .views import CustomLoginView

app_name = 'accounts'

urlpatterns = [
    path('login/', CustomLoginView.as_view(template_name="accounts/login.html"),name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name="logout"),
    path('signup/', views.SignUp.as_view(), name="signup"),
]

posts/urls.py
from django.urls import path,re_path
from . import views

app_name = 'posts'

urlpatterns = [
    path('',views.PostList.as_view(),name='all'),
    path('new/',views.CreateRegularPost.as_view(),name='create'),
    path('create/', views.CreatePost.as_view(), name='create_post'),
    re_path(r'^by/(?P<username>[-\w]+)$',views.UserPosts.as_view(),name='for_user'),
    re_path(r'^by/(?P<username>[-\w]+)/(?P<pk>\d+)$',views.PostDetail.as_view(),name='single'),
    re_path(r'^delete/(?P<pk>\d+)$',views.DeletePost.as_view(),name='delete'),
]

# path('newpost/',views.CreatePost.as_view(),name='group_post'),

zepharis/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("",views.HomePage.as_view(),name="home"),
    path('test/', views.TestPage.as_view(), name="test"),
    path('thanks/', views.ThanksPage.as_view(), name="thanks"),
    path("accounts/",include('accounts.urls',namespace='accounts')),
    path("accounts/",include('django.contrib.auth.urls')),
    path("posts/",include('posts.urls',namespace='posts')),
    path("groups/",include('groups.urls',namespace='groups')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ZEPHARIS</title>
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,300;1,400&family=Russo+One&display=swap" rel="stylesheet">

    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'zepharis/css/master.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">


</head>
<body >
    <nav class="navbar bg-body-tertiary fixed-top">
        <div class="container-fluid d-flex justify-content-center">
            <a class="navbar-brand" href="{% url 'home' %}">ZEPHARIS</a>
            <div class="container-fluid d-flex justify-content-end">
                <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
                </button>
                <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
                  <div class="offcanvas-header">
                    <h5 class="offcanvas-title" id="offcanvasNavbarLabel">Zepharis</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
                  </div>

                  <div class="offcanvas-body">
                      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                          {% if user.is_authenticated %}
                              <li class="nav-item dropdown">
                                  <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                      <i class="fas fa-user-circle fa-3x"></i>
                                  </a>
                                  <ul class="dropdown-menu">
                                  <li><a class="dropdown-item" href="{% url 'posts:for_user' username=user.username %}">@{{user.username}}</a></li>
                                  </ul>
                              </li>
                          
                              <li class="nav-item">
                                  <a class="nav-link active" href="{% url 'posts:create' %}">Create Post</a>
                              </li>
                              <li class="nav-item">
                                  <a class="nav-link active" href="{% url 'groups:all' %}">Groups</a>
                              </li>
                              <li class="nav-item">
                                  <a class="nav-link active" href="{% url 'groups:create' %}">Create Group</a>
                              </li>
                              <li class="nav-item">
                                  <a class="nav-link active" href="{% url 'accounts:logout' %}">Log Out</a>
                              </li>
      
                          {% else %}
                              <li class="nav-item">
                                  <a class="nav-link active" href="{% url 'groups:all' %}">Groups</a>
                              </li>
                              <li class="nav-item">
                                  <a class="nav-link active" href="{% url 'accounts:login' %}">Login</a>
                              </li>
                              <li class="nav-item">
                                  <a class="nav-link active" href="{% url 'accounts:signup' %}">Sign Up</a>
                              </li>
                          {% endif %}
              
          
                      </ul>
                  </div>
                </div>
              </div>
        </div>
        
        <div class="container">
            <h2>Welcome to Zepharis</h2>
        </div>
      </nav>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
    <div class="">

        {% block content %}

        {% endblock %}
        
    </div>

</body>

</html>

templates/index.html
{% extends "base.html" %}

{% block content %}
<div class="container">
    {% for post in posts %}
        <div class="card mb-3">
            <div class="card-body">
                <h5 class="card-title">{{ post.message }}</h5>
                {% if post.image %}
                    <img src="{{ post.image.url }}" alt="Post Image" class="card-img-top img-fluid">
                {% endif %}
                <p class="card-text">Created at: {{ post.created_at }}</p>
                <p class="card-text">Posted by: {{ post.user.username }}</p>
                <!-- Other post details -->
            </div>
        </div>
        <br>
    {% endfor %}
</div>

{% endblock %}


        

templates/test.html
{% extends "base.html" %}
{% block content %}
<div class="container">

</div>

{% endblock %}

templates/thanks.html
{% extends "base.html" %}
{% block content %}
<h1>Thanks for visiting! Come back soon!</h1>

{% endblock %}