posts/urls.py
from django.urls import path,re_path
from . import views

app_name = 'posts'

urlpatterns = [
    path('',views.PostList.as_view(),name='all'),
    path('new/',views.CreateRegularPost.as_view(),name='create'),
    path('create/', views.CreatePost.as_view(), name='create_post'),
    re_path(r'^by/(?P<username>[-\w]+)$',views.UserPosts.as_view(),name='for_user'),
    re_path(r'^by/(?P<username>[-\w]+)/(?P<pk>\d+)$',views.PostDetail.as_view(),name='single'),
    re_path(r'^delete/(?P<pk>\d+)$',views.DeletePost.as_view(),name='delete'),
]

# path('newpost/',views.CreatePost.as_view(),name='group_post'),

zepharis/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("",views.HomePage.as_view(),name="home"),
    path('test/', views.TestPage.as_view(), name="test"),
    path('thanks/', views.ThanksPage.as_view(), name="thanks"),
    path("accounts/",include('accounts.urls',namespace='accounts')),
    path("accounts/",include('django.contrib.auth.urls')),
    path("posts/",include('posts.urls',namespace='posts')),
    path("groups/",include('groups.urls',namespace='groups')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

posts/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings
from django.shortcuts import render


import misaka

from groups.models import Group

# Create your models here.
from django.contrib.auth import get_user_model
User = get_user_model()

class Post(models.Model):
    user = models.ForeignKey(User,related_name='posts', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now=True)
    message = models.TextField()
    group = models.ForeignKey(Group,related_name='group_posts',null=True,blank=True,on_delete=models.CASCADE)
    image = models.ImageField(upload_to='post_images/', blank=True, null=True)  # Add an ImageField
    message_html = models.TextField(editable=False)

    def __str__(self):
        return self.message
    
    def save(self,*args,**kwargs):
        self.message_html = misaka.html(self.message)
        super().save(*args,**kwargs)

    def get_absolute_url(self):
        return reverse('posts:single',kwargs={'username':self.user.username,'pk':self.pk})
    
    class Meta:
        ordering = ['-created_at']
        unique_together = ['user','message']

posts/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):
    image = forms.ImageField(required=False)  # Add an ImageField to the form

    class Meta:
        model = Post
        fields = ['message', 'image']  # Exclude the 'group' field from the form

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Set initial value for the message field to an empty string
        self.fields['message'].initial = ''

posts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy

from django.http import Http404
from django.views import generic

from braces.views import SelectRelatedMixin

from django.contrib import messages

from . import models
from .models import Post
from . import forms
from .forms import PostForm
from groups.models import Group

from django.contrib.auth import get_user_model
User = get_user_model()

# Create your views here.


class PostList(SelectRelatedMixin,generic.ListView):
    model = models.Post
    select_related = ('user','group')

class UserPosts(generic.ListView):
    model = models.Post
    template_name = 'posts/user_post_list.html'

    def get_queryset(self):
        try:
            self.post_user = User.objects.prefetch_related('posts').get(username__iexact=self.kwargs.get('username'))
        except User.DoesNotExist:
            raise Http404
        else:
            return self.post_user.posts.all()
        
    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        context['post_user'] = self.post_user
        return context
    

class PostDetail(SelectRelatedMixin,generic.DetailView):
    model = models.Post
    select_related = ('user','group')

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user__username__iexact=self.kwargs.get('username'))
    

class CreateRegularPost(LoginRequiredMixin, SelectRelatedMixin, generic.CreateView):
    form_class = PostForm  # Use the form for regular posts
    model = Post
    template_name = 'posts/post_form.html'  # Update with your actual template name for regular posts

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user

        # Check if an image file was uploaded
        if 'image' in self.request.FILES:
            self.object.image = self.request.FILES['image']  # Assign the uploaded image to the Post model field
        
        # Save the Post object with the uploaded image
        self.object.save()

        messages.success(self.request, 'Regular post created successfully.')
        return redirect('posts:single', username=self.request.user.username, pk=self.object.pk)

    # Other methods as needed

class CreatePost(LoginRequiredMixin, generic.CreateView):
    form_class = PostForm
    model = Post
    template_name = 'posts/group_post_form.html'  # Update with your actual template name

    def form_valid(self, form):
        group_id = self.request.POST.get('group')
        group = get_object_or_404(Group, id=group_id)

        if self.request.user in group.members.all():
            self.object = form.save(commit=False)
            self.object.user = self.request.user
            self.object.group = group

            # Handle the image upload
            if 'image' in self.request.FILES:
                self.object.image = self.request.FILES['image']

            self.object.save()

            messages.success(self.request, 'Post created successfully.')
            return redirect('posts:single', username=self.request.user.username, pk=self.object.pk)
        else:
            form.add_error(None, 'You are not a member of this group. Cannot create a post.')
            return self.render_to_response(self.get_context_data(form=form))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['groups'] = Group.objects.all()  # Provide groups to the template
        return context

class DeletePost(LoginRequiredMixin,SelectRelatedMixin,generic.DeleteView):

    model = models.Post
    select_related = ('user','group')
    success_url = reverse_lazy('posts:all')

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user_id = self.request.user.id)
    
    def delete(self,*args,**kwargs):
        messages.success(self.request,'Post Deleted')
        return super().delete(*args,**kwargs)

posts/templates/posts/_post.html
<div class="post media">
    
    <div class="card mb-3">
        <div class="card-body">
            <h5 class="card-title">{{ post.message }}</h5>
            {% if post.image %}
                <img src="{{ post.image.url }}" alt="Post Image" class="card-img-top img-fluid">
            {% endif %}
        </div>
    </div>

    <div class="media-body">
        <!-- <strong>{{post.user.username}}</strong> -->
        <h5 class="media-heading">
        <span class="username">
            <a href="{% url 'posts:for_user' username=post.user.username %}">@{{post.user.username}}</a>
        </span>
        <time class="time">
            <a href="{% url 'posts:single' username=post.user.username pk=post.pk %}">
                {{post.created_at}}
            </a>
        </time>
        </h5>

        <div class="media-footer">
            {% if user.is_authenticated and post.user == user %}
            <a href="{% url 'posts:delete' pk=post.pk %}" title="delete" class="btn btn-simple">
                <span class="text-danger" aria-hidden="true">
                    <i class="fas fa-trash"></i>Delete
                </span>  
            </a>
            {% endif %}

        </div>

    </div>

</div>

posts/templates/posts/group_post_form.html
{% extends "posts/post_base.html" %}


{% load bootstrap5 %}

{% block post_content %}

    <h4>Create a new Post</h4>
    <form id="postForm" action="{% url 'posts:create_post' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.non_field_errors }}
        
        <!-- Render the message field -->
        <!-- Render the message field manually with Bootstrap 5 styling -->

        <div class="mb-3">
            <label for="{{ form.image.id_for_label }}" class="form-label">Image</label>
            {{ form.image }}
            {% if form.image.help_text %}
                <div class="form-text">{{ form.image.help_text|safe }}</div>
            {% endif %}
        </div>

        <div class="mb-3">
            <label for="{{ form.message.id_for_label }}" class="form-label">Message</label>
            <textarea class="form-control" id="{{ form.message.id_for_label }}" name="{{ form.message.name }}" required>{{ form.message.value|default:'' }}</textarea>
            {% if form.message.help_text %}
                <div class="form-text">{{ form.message.help_text|safe }}</div>
            {% endif %}
        </div>

        <div class="mb-3">
            <label for="{{ form.group.id_for_label }}" class="form-label">{{ form.group.label }}</label>
            <select class="form-select" id="group" name="group" required>
                {% for group in groups %}
                    <option value="{{ group.id }}">{{ group.name }}</option>
                {% endfor %}
            </select>
            {% if form.group.help_text %}
                <div class="form-text">{{ form.group.help_text|safe }}</div>
            {% endif %}
        </div>
        

        <br>
        {% buttons %}
            <button type="submit" class="btn btn-primary btn-large">Post</button>
        {% endbuttons %}
    </form>
{% endblock %}

posts/templates/posts/post_base.html
{% extends "base.html" %}

{% block content %}
<div class="posts-page">
    <div class="container post-container" >
        <div class="row">
            {% block prepost %}{% endblock %}
            {% block post_content %}{% endblock %}
            {% block post_post %}{% endblock %}
        </div>
    </div>
</div>

{% endblock %}

posts/templates/posts/post_confirm_delete.html
{% extends 'posts/post_base.html' %}

{% block post_content %}
<h3>Are you sure you want to delete this post?</h3>

<div class="posts">
    {% include 'posts/_post.html' with post=object hide_delete=True %}
</div>
<form method="post">
    {% csrf_token %}
    <input type="submit" value="Confirm Delete" class="btn btn-dnger btn-large">
    <a href="{% url 'posts:single' username=user.username pk=object.pk %}"
    class="btn btn-simple btn-large btn-default">Cancel</a>
</form>
{% endblock %}

posts/templates/posts/post_detail.html
{% extends 'posts/post_base.html' %}

{% block post_content %}
<div class="col-md-8">
    {% include 'posts/_post.html' %}
</div>

{% endblock %}

posts/templates/posts/post_form.html
{% extends "posts/post_base.html" %}

{% load bootstrap5 %}

{% block post_content %}
    <h4>Create a new Post</h4>
    <form id="postForm" action="{% url 'posts:create' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.non_field_errors }}
        
        <!-- Render the message field -->
        <!-- Render the message field manually with Bootstrap 5 styling -->

        <div class="mb-3">
            <label for="{{ form.image.id_for_label }}" class="form-label">Image</label>
            {{ form.image }}
            {% if form.image.help_text %}
                <div class="form-text">{{ form.image.help_text|safe }}</div>
            {% endif %}
        </div>

        <div class="mb-3">
            <label for="{{ form.message.id_for_label }}" class="form-label">Message</label>
            <textarea class="form-control" id="{{ form.message.id_for_label }}" name="{{ form.message.name }}" required>{{ form.message.value|default:'' }}</textarea>
            {% if form.message.help_text %}
                <div class="form-text">{{ form.message.help_text|safe }}</div>
            {% endif %}
        </div>


        {% buttons %}
            <button type="submit" class="btn btn-primary btn-large">Post</button>
        {% endbuttons %}
    </form>
{% endblock %}

posts/templates/posts/post_list.html
{% extends "posts/post_base.html" %}

{% block pre_post_content %}
<div class="col-md-4">
    {% if request.user.is_authenticated %}
    <div class="card-with-shadow">
        <div class="content">
            <h5 class="title">Your Groups</h5>
            <ul class="list-unstyled">
                {% for member_group in get_user_groups %}
                <li class="group li-with-bullet">
                    <a href="{% url 'groups:single' slug=member_group.group.slug %}"></a>
                </li>
                {% endfor %}
            </ul>
        </div>
    </div>
    {% endif %}
    <div class="card card-with-shadow">
        <div class="content">
            <h5 class="title">All Groups</h5>
            <ul class="list-unstyled"></ul>
            {% for other_group in get_other_groups %}
            <li class="group li-with-bullet">
                <a href="{% url 'groups:single' slug=other_group.slug %}"></a>
            </li>
            {% endfor %}

        </div>

    </div>

</div>
{% endblock %}

{% block post_content %}
<div class="col-md-8">
    {% for post in post_list %}
        {% include 'posts/_post.html' %}
    {% endfor %}

</div>
{% endblock %}

posts/templates/posts/user_post_list.html
{% extends 'posts/post_base.html' %}

{% block prepost %}
<div class="col-md-4">
    <h1>@{{post_user.username}}</h1>
</div>

{% endblock %}

{% block post_content %}
<div class="col-md-8">
    <div class="container">
        {% for post in post_list %}
            <div class="card mb-3">
                <div class="card-body">
                    <h5 class="card-title">{{ post.message }}</h5>
                    {% if post.image %}
                        <img src="{{ post.image.url }}" alt="Post Image" class="card-img-top img-fluid">
                    {% endif %}
                    <div class="media-body">
                        <!-- <strong>{{post.user.username}}</strong> -->
                        <h5 class="media-heading">
                        <span class="username">
                            <a href="{% url 'posts:for_user' username=post.user.username %}">@{{post.user.username}}</a>
                        </span>
                        <time class="time">
                            <a href="{% url 'posts:single' username=post.user.username pk=post.pk %}">
                                {{post.created_at}}
                            </a>
                        </time>
                        </h5>
                
                        <div class="media-footer">
                            {% if user.is_authenticated and post.user == user %}
                            <a href="{% url 'posts:delete' pk=post.pk %}" title="delete" class="btn btn-simple">
                                <span class="text-danger" aria-hidden="true">
                                    <i class="fas fa-trash"></i>Delete
                                </span>  
                            </a>
                            {% endif %}
                
                        </div>
                    <!-- Other post details -->
                </div>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}